<?php

namespace MeetupBundle\Repository;

/**
 * AppleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppleRepository extends \Doctrine\ORM\EntityRepository
{
}
